cargo-features = ["strip"]

[package]
name = "ft_linear_regression"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "^0.3.1"

[profile.release]
strip = true
lto = true
codegen-units = 1